server:
  port: 8100

spring:
  application:
    name: iot-gateway
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
        server-addr: 127.0.0.1:8848
        file-extension: yml
      discovery:
        server-addr: 127.0.0.1:8848
        namespace:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
      # 认证模块
        - id: iot-auth
          uri: lb://iot-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      # 用户模块
        - id: iot-system
          uri: lb://iot-system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true



